services:
  - type: web
    name: agripartners
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_KEY
        value: agripartners-demo-key
      - key: NEAR_NETWORK
        value: testnet
      - key: NEAR_ADMIN_ACCOUNT
        value: farab.testnet
      - key: NEAR_ADMIN_PRIVATE_KEY
        value: ed25519:4gCA8Ap84nuAXsu3Rda1Rjtd425zqmSPF665xJA3MQxY3TuviyYDtCV8HzL2d3iic799C4gKqZohZvjU6Thwg1XH
      - key: WASM_PATH
        value: ./contract/agripartners.wasm
      - key: DATABASE_URL
        sync: false
